name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

env:
  APP_LOCATION: "/dist" # Astro builds to /dist
  ARTIFACT_LOCATION: "dist" # Astro builds to /dist
  OUTPUT_LOCATION: "dist" # Astro builds to /dist

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    environment: Production
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - uses: actions/setup-node@v3
        with:
          node-version: 18.17.x
          cache: 'npm'
      - run: npm install
      - run: npm run build -mode production
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_TREE_0FE191203 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          skip_app_build: true
          skip_api_build: true
          app_artifact_location: ${{ env.ARTIFACT_LOCATION }}
          output_location: "dist"
